CREATE OR REPLACE PROCEDURE CTS_EMPLOYEE_PROC(
    P_FIRST_NAME        IN  CTS_EMPLOYEES.FIRSTNAME%TYPE,
    P_MIDDLE_NAME       IN  CTS_EMPLOYEES.MIDDLENAME%TYPE,
    P_LAST_NAME         IN  CTS_EMPLOYEES.LASTNAME%TYPE,
    P_EMP_CUR           OUT SYS_REFCURSOR
)
AS
BEGIN
    OPEN P_EMP_CUR FOR 
        SELECT ID, FIRSTNAME, MIDDLENAME, LASTNAME, DOJ
          FROM CTS_EMPLOYEES
         WHERE FIRSTNAME  = NVL(P_FIRST_NAME, FIRSTNAME)
           AND MIDDLENAME = NVL(P_MIDDLE_NAME, MIDDLENAME)
           AND LASTNAME   = NVL(P_LAST_NAME, LASTNAME);
EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE(SQLCODE || ': ' || SQLERRM);
END CTS_EMPLOYEE_PROC;